In [1]:
import sys; sys.path.append('..') # add project root to the python path

In [2]:
from src.common.gridworld import GridworldEnv # Gridworld Environment

In [3]:
num_y, num_x = 4, 4
env = GridworldEnv(shape=[num_y, num_x])

In [4]:
observation_space = env.observation_space
action_space = env.action_space
print("Number of states: {}".format(observation_space))
print("Number of actions: {}".format(action_space))

Number of states: Discrete(16)
Number of actions: Discrete(4)


In [5]:
import numpy as np # 파이썬에서 계산과학 및 수학계산을 위해서 많이 사용되는 라이브러리인 `numpy`를 불러옵니다.

In [6]:
num_row = 2
num_col = 2 

# [num_row x now_col] 행렬을 만듭니다. 이때 행렬의 각 원소는 임의의 값으로 채워집니다.
rank2_tensor = np.random.random(size=(num_row,num_col)) 

In [7]:
print(rank2_tensor)

[[0.30604985 0.89335383]
 [0.26838695 0.90272819]]


In [8]:
tesor_shape = rank2_tensor.shape
tensor_rank = len(tesor_shape)
print("Tensor shape : {}".format(tesor_shape))
print("Tensor rank : {}".format(tensor_rank))

Tensor shape : (2, 2)
Tensor rank : 2


In [9]:
P = env.P_tensor
print("P shape : {}".format(P.shape))

P shape : (4, 16, 16)


In [10]:
# 행동 '상'(인덱스0)을 선택했을때 현재상태에서 다음상태로 전이하는 확률을 나타냄.
action_up_prob = P[0, :, :]

In [11]:
print(action_up_prob) 

[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]


In [12]:
action_up_prob >= 0

array([[ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  Tru

In [13]:
is_greater_than_0 = action_up_prob >= 0
is_all_greater_than_0 = is_greater_than_0.sum() == is_greater_than_0.size

In [14]:
is_all_greater_than_0

True

In [15]:
action_up_prob.sum(axis=1) # 2 번째 축으로 합을 계산합니다. 파이썬은 숫자를 0부터 셉니다.

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [16]:
action_up_prob.sum(axis=-1) # '마지막' 축으로 합을 계산합니다.

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [17]:
R = env.R_tensor
print(R)

[[ 0.  0.  0.  0.]
 [-1. -1. -1. -1.]
 [-1. -1. -1. -1.]
 [-1. -1. -1. -1.]
 [-1. -1. -1. -1.]
 [-1. -1. -1. -1.]
 [-1. -1. -1. -1.]
 [-1. -1. -1. -1.]
 [-1. -1. -1. -1.]
 [-1. -1. -1. -1.]
 [-1. -1. -1. -1.]
 [-1. -1. -1. -1.]
 [-1. -1. -1. -1.]
 [-1. -1. -1. -1.]
 [-1. -1. -1. -1.]
 [ 0.  0.  0.  0.]]


In [18]:
_ = env.reset() # Gridworld 를 초기화합니다.
print("Current position index : {}".format(env.s))

Current position index : 13


In [19]:
# 좀 더 직관적인 가시화를 위해서 action 인덱스를 방향으로 바꿔줍니다.
action_mapper = {
    0: 'UP',
    1: 'RIGHT',
    2: 'DOWN',
    3: 'LEFT'
}

In [20]:
step_counter = 0
while True:
    # [0,4) 에서 정수값 1개를 임의로 선택합니다. 기본적인 설정이 high 값은 포함하지 않는다는 것에 유의!        
    print("At t = {}".format(step_counter))
    env._render()
    
    cur_state = env.s
    action = np.random.randint(low=0, high=4)
    next_state, reward, done, info = env.step(action)    
    
    print("state : {}".format(cur_state))
    print("aciton : {}".format(action_mapper[action]))
    print("reward : {}".format(reward))
    print("next state : {} \n".format(next_state))
    step_counter += 1
    if done:
        break

At t = 0
T  o  o  o
o  o  o  o
o  o  o  o
o  x  o  T
state : 13
aciton : RIGHT
reward : -1.0
next state : 14 

At t = 1
T  o  o  o
o  o  o  o
o  o  o  o
o  o  x  T
state : 14
aciton : DOWN
reward : -1.0
next state : 14 

At t = 2
T  o  o  o
o  o  o  o
o  o  o  o
o  o  x  T
state : 14
aciton : RIGHT
reward : -1.0
next state : 15 



In [21]:
def run_episode(env, s0):
    _ = env.reset() # Gridworld 를 초기화합니다.
    env.s = s0
    
    step_counter = 0
    while True:
        action = np.random.randint(low=0, high=4)
        next_state, reward, done, info = env.step(action)

        step_counter += 1
        if done:
            break
    return step_counter

In [22]:
n_episodes = 10
s0 = 6

for i in range(n_episodes):
    len_ep = run_episode(env, s0)
    print("Episode {} | Length of episode : {}".format(i, len_ep))

Episode 0 | Length of episode : 10
Episode 1 | Length of episode : 7
Episode 2 | Length of episode : 23
Episode 3 | Length of episode : 28
Episode 4 | Length of episode : 6
Episode 5 | Length of episode : 5
Episode 6 | Length of episode : 13
Episode 7 | Length of episode : 20
Episode 8 | Length of episode : 7
Episode 9 | Length of episode : 21
